# Generated by Django 3.1.3 on 2020-11-15 23:10

from django.db import migrations, models
import django.db.models.deletion
import redcycle.enums.CategoryEnum


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('creationDate', models.DateTimeField()),
                ('available', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('FURNITURE', 'FURNITURE'), ('ELECTRONICS', 'ELECTRONICS'), ('CLOTHES', 'CLOTHES'), ('FOOD', 'FOOD'), ('OTHER', 'OTHER')], default=redcycle.enums.CategoryEnum.CategoryEnum['OTHER'], max_length=30)),
                ('authorUuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redcycle.account')),
                ('locationUuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='redcycle.location')),
            ],
        ),
    ]
